#!/bin/sh

MODDIR="/lib/modules/$(uname -r)/extra"

case "$1" in
start)
    echo "Loading misc-modules: hello and faulty"
    # module_load expects to be run from the directory containing the .ko file
    (cd $MODDIR && /usr/bin/module_load hello)
    (cd $MODDIR && /usr/bin/module_load faulty)
    ;;
stop)
    echo "Unloading misc-modules: hello and faulty"
    /usr/bin/module_unload faulty
    /usr/bin/module_unload hello
    ;;
*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
